return require("lazy").setup({
  require("plugins.theme"),
  require("plugins.lsp"),
  require("plugins.autopairs"),
  require("plugins.cmp"),
  require("plugins.treesitter"),
  require("plugins.flutter"),
  require("plugins.oil"),
  require("plugins.toggleterm"),
  require("plugins.formatter"),
  require("plugins.surround"),
  require("plugins.markdown"),
  require("plugins.colorizer"),
  require("plugins.lualine"),
  require("plugins.modes"),
  require("plugins.telescope"),
  require("plugins.leap"),
  require("plugins.git"),
  require("plugins.trouble"),
  require("plugins.tree"),
  require("plugins.saga"),
  require("plugins.better-escape"),
  require("plugins.numb"),
  require("plugins.dap"),
  require("plugins.git-conflict"),
  require("plugins.overseer"),
  require("plugins.d2"),
}, {
  install = { missing = false },
  checker = { enabled = false },
  change_detection = { enabled = false },
  lockfile = vim.fn.stdpath("state") .. "/lazy-lock.json",
})
