return require("lazy").setup({
  require("plugins.theme"),
  require("plugins.lsp"),
  require("plugins.autopairs"),
  require("plugins.cmp"),
  require("plugins.treesitter"),
  require("plugins.flutter"),
  require("plugins.oil"),
  require("plugins.toggleterm"),
  require("plugins.formatter"),
  require("plugins.surround"),
  require("plugins.colorizer"),
  require("plugins.lualine"),
  require("plugins.modes"),
  require("plugins.fzf"),
  require("plugins.leap"),
  require("plugins.git"),
  require("plugins.trouble"),
  require("plugins.tree"),
  require("plugins.saga"),
  require("plugins.better-escape"),
  require("plugins.numb"),
  require("plugins.dap"),
  require("plugins.diffview"),
  require("plugins.overseer"),
  require("plugins.d2"),
  require("plugins.yazi"),
  require("plugins.markdown-ai"),
  require("plugins.markdown-ai-init"),
  require("plugins.markdown-render"),
  require("plugins.markdown-export"),
  -- require("plugins.markdown-ai-prompts"),
  -- require("plugins.markdown-ai-providers"),
  --  require("plugins.markdown-ai-detector"),
  require("plugins.smear-cursor"),
  require("plugins.rust"),
  require("plugins.aerial"),
  require("plugins.blamer"),
  require("plugins.grug-far"),
  require("plugins.refactoring"),
  require("plugins.spectre"),
  require("plugins.todo"),
  require("plugins.dropbar"),
  require("plugins.multi-cursor"),
  require("plugins.flash"),
}, {
  install = { missing = false },
  checker = { enabled = false },
  change_detection = { enabled = false },
  lockfile = vim.fn.stdpath("state") .. "/lazy-lock.json",
})
